const INLINE_COMMENT_REQUEST = 'vali-ah-frontend/inlineComment/INLINE_COMMENT_REQUEST';
const INLINE_COMMENT_SUCCESS = 'vali-ah-frontend/inlineComment/INLINE_COMMENT_SUCCESS';
const INLINE_COMMENT_FAILURE = 'vali-ah-frontend/inlineComment/INLINE_COMMENT_FAILURE';
const INLINE_COMMENT_CLEAR = 'vali-ah-frontend/inlineComment/INLINE_COMMENT_CLEAR';

export {
  INLINE_COMMENT_REQUEST, INLINE_COMMENT_SUCCESS, INLINE_COMMENT_FAILURE, INLINE_COMMENT_CLEAR
};
