const REQUEST_PROFILE_SUCCESS = 'vali-ah-frontend/profileView/REQUEST_PROFILE_SUCCESS';
const PROFILE_FAILURE = 'vali-ah-frontend/profileView/PROFILE_FAILURE';
const PROFILE_ISLOADING = 'vali-ah-frontend/profileView/PROFILE_ISLOADING';
const REQUEST_PROFILE_UPDATE_SUCCESS = 'vali-ah-frontend/profileUpdate/REQUEST_PROFILE_UPDATE_SUCCESS';
const PROFILE_IS_UPDATING = 'vali-ah-frontend/profileUpdate/PROFILE_IS_UPDATING';
const PROFILE_UPDATE_FAILURE = 'vali-ah-frontend/profileUpdate/PROFILE_UPDATE_FAILURE';

export {
  REQUEST_PROFILE_SUCCESS,
  PROFILE_FAILURE,
  PROFILE_ISLOADING,
  REQUEST_PROFILE_UPDATE_SUCCESS,
  PROFILE_IS_UPDATING,
  PROFILE_UPDATE_FAILURE,
};
