const GET_PROFILE_REQUEST = 'vali-ah-frontend/profileView/GET_PROFILE_REQUEST';
const GET_PROFILE_REQUEST_SUCCESS = 'vali-ah-frontend/profileView/GET_PROFILE_REQUEST_SUCCESS';
const GET_PROFILE_FAILURE = 'vali-ah-frontend/profileView/GET_PROFILE_FAILURE';
const GET_PROFILE_REQUEST_UPDATE = 'vali-ah-frontend/profileUpdate/GET_PROFILE_REQUEST_UPDATE';
const GET_PROFILE_REQUEST_UPDATE_SUCCESS = 'vali-ah-frontend/profileUpdate/GET_PROFILE_REQUEST_UPDATE_SUCCESS';
const GET_PROFILE_UPDATE_FAILURE = 'vali-ah-frontend/profileUpdate/GET_PROFILE_UPDATE_FAILURE';

export {
  GET_PROFILE_REQUEST,
  GET_PROFILE_REQUEST_SUCCESS,
  GET_PROFILE_FAILURE,
  GET_PROFILE_REQUEST_UPDATE,
  GET_PROFILE_REQUEST_UPDATE_SUCCESS,
  GET_PROFILE_UPDATE_FAILURE,
};
