const REQUEST_SEARCH = 'REQUEST_SEARCH';
const SEARCH_ARTICLES_SUCCESS = 'SEARCH_ARTICLES_SUCCESS';
const SEARCH_ARTICLES_FAILURE = 'SEARCH_ARTICLES_FAILURE';
const SEARCH_ARTICLES_REQUEST = 'SEARCH_ARTICLES_REQUEST';

export {
  REQUEST_SEARCH,
  SEARCH_ARTICLES_SUCCESS,
  SEARCH_ARTICLES_FAILURE,
  SEARCH_ARTICLES_REQUEST,
};
