const REQUEST_SEARCH = 'vali-ah-frontend/search/REQUEST_SEARCH';
const SEARCH_ARTICLES_SUCCESS = 'vali-ah-frontend/search/SEARCH_ARTICLES_SUCCESS';
const SEARCH_ARTICLES_ERROR = 'vali-ah-frontend/search/SEARCH_ARTICLES_ERROR';
const SEARCH_ARTICLES_REQUEST = 'vali-ah-frontend/search/SEARCH_ARTICLES_REQUEST';

export {
  REQUEST_SEARCH,
  SEARCH_ARTICLES_SUCCESS,
  SEARCH_ARTICLES_ERROR,
  SEARCH_ARTICLES_REQUEST,
};
