const PASSWORD_RESET_REQUEST = 'vali-ah-frontend/passwordReset/PASSWORD_RESET_REQUEST';
const PASSWORD_UPDATE_REQUEST = 'vali-ah-frontend/passwordReset/PASSWORD_UPDATE_REQUEST';
const PASSWORD_RESET_SUCESS = 'vali-ah-frontend/passwordReset/PASSWORD_RESET_SUCESS';
const PASSWORD_RESET_FAILURE = 'vali-ah-frontend/passwordReset/PASSWORD_RESET_FAILURE';


export {
  PASSWORD_RESET_REQUEST, PASSWORD_UPDATE_REQUEST, PASSWORD_RESET_SUCESS, PASSWORD_RESET_FAILURE
};
