const VOTE_ARTICLE_REQUEST = 'VOTE_ON_ARTICLE';
const VOTE_ARTICLE_SUCCESS = 'VOTE_SUCCESSFULL';
const VOTE_ARTICLE_COUNT = 'ARTICLE_VOTE_COUNT';

export { VOTE_ARTICLE_REQUEST, VOTE_ARTICLE_SUCCESS, VOTE_ARTICLE_COUNT };
