import { decodeString } from './characterCounter';

/* eslint-disable consistent-return */
/* eslint-disable array-callback-return */
export const paragraphBlock = (obj) => {
  const newString = decodeString(obj.data.text);
  return `
<div class="ce-block">
  <div class="ce-block__content">
    <div class="ce-paragraph cdx-block">
      <p>${newString}</p>
    </div>
  </div>
</div>
`;
};

export const imageBlock = (obj) => `
<div class="ce-block">
  <div class="ce-block__content">
    <div class="ce-paragraph cdx-block">
      <img src="${obj.data.file.url}" alt="${obj.data.caption}" />
      <div class="text-center">
        <i>${obj.data.caption}</i>
      </div>
    </div>
  </div>
</div>
`;

export const headerBlock = (obj) => {
  const newString = decodeString(obj.data.text);

  return `
<div class="ce-block">
  <div class="ce-block__content">
    <div class="ce-paragraph cdx-block">
      <h${obj.data.level}>${newString}</h${obj.data.level}>
    </div>
  </div>
</div>
`;
};


/**
 * function to change code generated by editor.js to HTML
 *
 * @param {Array} block block returned from editor.js
 */
function blockToHtmlConverter(block) {
  let articleHTML = '';

  block.map((obj) => {
    switch (obj.type) {
    case 'paragraph':
      articleHTML += paragraphBlock(obj);
      break;
    case 'image':
      articleHTML += imageBlock(obj);
      break;
    case 'header':
      articleHTML += headerBlock(obj);
      break;
    default:
      return '';
    }
  });

  return articleHTML;
}

export default blockToHtmlConverter;
