const FETCH_ARTICLE_LOADING = 'FETCH_ARTICLE_LOADING';
const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
const FETCH_ARTICLE_FAILURE = 'FETCH_ARTICLE_FAILURE';

export {
  FETCH_ARTICLE_LOADING,
  FETCH_ARTICLE_SUCCESS,
  FETCH_ARTICLE_FAILURE
};
