const LOGIN_USER = 'LOGIN_USER';
const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS';
const LOGIN_RESET = 'LOGIN_RESET';
const LOGIN_ERROR = 'LOGIN_ERROR';
const ERROR_RESET = 'ERROR_RESET';

export {
  LOGIN_USER, LOGIN_IN_PROGRESS, LOGIN_RESET,
  LOGIN_ERROR, ERROR_RESET
};
